# Generated by Django 2.1.3 on 2018-11-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='price',
            field=models.FloatField(),
        ),
    ]
